import { StyleSheet } from "react-native";
import { Colors } from "../../constants/Colors";

export const styles = StyleSheet.create({
    safe: { flex: 1, backgroundColor: Colors.surface },
    kav: { flex: 1 },
    scroll: { padding: 28, paddingTop: 40 },
    logoRow: { flexDirection: "row", alignItems: "center", gap: 12, marginBottom: 40 },
    logoBox: {
        width: 44,
        height: 44,
        borderRadius: 14,
        alignItems: "center",
        justifyContent: "center",
    },
    appName: { fontSize: 22, fontWeight: "500", color: Colors.onSurface, letterSpacing: -0.5 },
    heading: { fontSize: 30, fontWeight: "500", color: Colors.onSurface, letterSpacing: -0.5, marginBottom: 6 },
    subheading: { fontSize: 14, color: Colors.onSurfaceVariant, marginBottom: 32, lineHeight: 20 },
    form: { gap: 16 },
    field: { gap: 6 },
    fieldLabel: { fontSize: 11, fontWeight: "500", color: Colors.onSurfaceVariant, letterSpacing: 0.2 },
    input: {
        backgroundColor: Colors.surfaceLow,
        borderRadius: 14,
        paddingHorizontal: 16,
        paddingVertical: 14,
        fontSize: 14,
        color: Colors.onSurface,
        borderWidth: 2,
        borderColor: "transparent",
    },
    handleRow: {
        flexDirection: "row",
        alignItems: "center",
        backgroundColor: Colors.surfaceLow,
        borderRadius: 14,
        borderWidth: 2,
        borderColor: "transparent",
    },
    atSign: { paddingLeft: 16, fontSize: 15, fontWeight: "600", color: Colors.onSurfaceVariant },
    handleInput: { flex: 1, backgroundColor: "transparent", borderWidth: 0 },
    toggleRow: { flexDirection: "row", alignItems: "center", gap: 4, paddingVertical: 4 },
    toggleText: { fontSize: 13, color: Colors.onSurfaceVariant },
    toggleLink: { fontSize: 13, fontWeight: "600", color: Colors.primary },
    btnWrapper: { marginTop: 8, borderRadius: 18, overflow: "hidden" },
    btn: {
        flexDirection: "row",
        alignItems: "center",
        justifyContent: "center",
        gap: 10,
        paddingVertical: 16,
        paddingHorizontal: 24,
    },
    btnText: { fontSize: 15, fontWeight: "500", color: Colors.onPrimary },
});
