import { StyleSheet } from "react-native";
import { Colors } from "../../constants/Colors";

export const styles = StyleSheet.create({
    safe: { flex: 1, backgroundColor: Colors.surface },
    scroll: { paddingBottom: 40 },
    header: {
        flexDirection: "row",
        alignItems: "center",
        justifyContent: "space-between",
        paddingHorizontal: 20,
        paddingTop: 12,
        paddingBottom: 16,
    },
    title: { fontSize: 22, fontWeight: "500", color: Colors.onSurface, letterSpacing: -0.5 },
    editBtn: {
        flexDirection: "row",
        alignItems: "center",
        gap: 6,
        paddingHorizontal: 14,
        paddingVertical: 8,
        borderRadius: 12,
        backgroundColor: Colors.surfaceLow,
    },
    editBtnText: { fontSize: 13, fontWeight: "700", color: Colors.primary },
    avatarSection: { alignItems: "center", paddingVertical: 24, gap: 16 },
    avatarWrapper: { position: "relative" },
    cameraOverlay: {
        position: "absolute",
        inset: 0,
        borderRadius: 50,
        backgroundColor: "rgba(0,0,0,0.45)",
        alignItems: "center",
        justifyContent: "center",
    },
    userInfo: { alignItems: "center", gap: 4 },
    userName: { fontSize: 20, fontWeight: "500", color: Colors.onSurface, letterSpacing: -0.3 },
    userHandle: { fontSize: 14, fontWeight: "500", color: Colors.primary },
    userEmail: { fontSize: 13, color: Colors.onSurfaceVariant, opacity: 0.7 },
    userBio: {
        fontSize: 13,
        color: Colors.onSurfaceVariant,
        textAlign: "center",
        maxWidth: 280,
        marginTop: 8,
        lineHeight: 19,
    },
    form: { paddingHorizontal: 20, gap: 16 },
    field: { gap: 6 },
    fieldLabel: { fontSize: 10, fontWeight: "800", letterSpacing: 1, color: Colors.onSurfaceVariant, opacity: 0.6 },
    input: {
        backgroundColor: Colors.surfaceHigh,
        borderRadius: 14,
        paddingHorizontal: 16,
        paddingVertical: 13,
        fontSize: 14,
        color: Colors.onSurface,
    },
    handleRow: {
        flexDirection: "row",
        alignItems: "center",
        backgroundColor: Colors.surfaceHigh,
        borderRadius: 14,
    },
    atSign: { paddingLeft: 16, fontSize: 15, fontWeight: "500", color: Colors.onSurfaceVariant },
    handleInput: { flex: 1, backgroundColor: "transparent" },
    bioInput: { minHeight: 90, textAlignVertical: "top" },
    saveWrapper: { borderRadius: 16, overflow: "hidden", marginTop: 4 },
    saveBtn: { paddingVertical: 15, alignItems: "center" },
    saveBtnText: { fontSize: 15, fontWeight: "700", color: Colors.onPrimary },
    cancelBtn: { alignItems: "center", paddingVertical: 12 },
    cancelBtnText: { fontSize: 14, fontWeight: "600", color: Colors.onSurfaceVariant },
    signOutSection: {
        marginTop: 32,
        marginHorizontal: 20,
        borderTopWidth: 1,
        borderTopColor: Colors.surfaceHigh,
        paddingTop: 16,
    },
    signOutBtn: {
        flexDirection: "row",
        alignItems: "center",
        justifyContent: "center",
        backgroundColor: "#ffaaaa33",
        gap: 10,
        padding: 14,
        borderRadius: 14,
    },
    signOutText: { fontSize: 14, fontWeight: "500", color: Colors.error },
    optionsSection: {
        marginTop: 24,
        marginHorizontal: 20,
        backgroundColor: Colors.surfaceLowest,
        borderRadius: 16,
        overflow: "hidden",
    },
    optionRow: {
        flexDirection: "row",
        alignItems: "center",
        padding: 16,
        borderBottomWidth: 1,
        borderBottomColor: Colors.surfaceHigh,
    },
    optionIcon: {
        width: 32,
        height: 32,
        borderRadius: 10,
        backgroundColor: "#f1f1f1ff",
        alignItems: "center",
        justifyContent: "center",
        marginRight: 12,
    },
    optionText: {
        flex: 1,
        fontSize: 15,
        color: Colors.onSurfaceVariant,
    },
});
