export const dummyStoriesData = [
    {
        user: {
            _id: "user_1",
            name: "Ethan Parker",
            handle: "ethanparker",
            avatar: "https://i.pravatar.cc/150?img=12",
        },
        stories: [
            {
                _id: "story_1",
                user: {
                    _id: "user_1",
                    name: "Ethan Parker",
                    handle: "ethanparker",
                    avatar: "https://i.pravatar.cc/150?img=12",
                },
                mediaUrl: "https://picsum.photos/id/1011/800/1200",
                mediaType: "image",
                createdAt: "2026-06-01T10:53:04.242Z",
            },
            {
                _id: "story_2",
                user: {
                    _id: "user_1",
                    name: "Ethan Parker",
                    handle: "ethanparker",
                    avatar: "https://i.pravatar.cc/150?img=12",
                },
                mediaUrl: "https://picsum.photos/id/1015/800/1200",
                mediaType: "image",
                createdAt: "2026-06-01T12:15:00.000Z",
            },
        ],
    },
    {
        user: {
            _id: "user_2",
            name: "Olivia Bennett",
            handle: "oliviabennett",
            avatar: "https://i.pravatar.cc/150?img=13",
        },
        stories: [
            {
                _id: "story_3",
                user: {
                    _id: "user_2",
                    name: "Olivia Bennett",
                    handle: "oliviabennett",
                    avatar: "https://i.pravatar.cc/150?img=13",
                },
                mediaUrl: "https://picsum.photos/id/1025/800/1200",
                mediaType: "image",
                createdAt: "2026-06-01T09:45:00.000Z",
            },
        ],
    },
    {
        user: {
            _id: "user_3",
            name: "Liam Carter",
            handle: "liamcarter",
            avatar: "https://i.pravatar.cc/150?img=14",
        },
        stories: [
            {
                _id: "story_4",
                user: {
                    _id: "user_3",
                    name: "Liam Carter",
                    handle: "liamcarter",
                    avatar: "https://i.pravatar.cc/150?img=14",
                },
                mediaUrl: "https://picsum.photos/id/1043/800/1200",
                mediaType: "image",
                createdAt: "2026-06-01T08:20:00.000Z",
            },
        ],
    },
    {
        user: {
            _id: "user_4",
            name: "Sophia Reed",
            handle: "sophiareed",
            avatar: "https://i.pravatar.cc/150?img=15",
        },
        stories: [
            {
                _id: "story_5",
                user: {
                    _id: "user_4",
                    name: "Sophia Reed",
                    handle: "sophiareed",
                    avatar: "https://i.pravatar.cc/150?img=15",
                },
                mediaUrl: "https://picsum.photos/id/1050/800/1200",
                mediaType: "image",
                createdAt: "2026-06-01T11:00:00.000Z",
            },
            {
                _id: "story_6",
                user: {
                    _id: "user_4",
                    name: "Sophia Reed",
                    handle: "sophiareed",
                    avatar: "https://i.pravatar.cc/150?img=15",
                },
                mediaUrl: "https://picsum.photos/id/1060/800/1200",
                mediaType: "image",
                createdAt: "2026-06-01T11:30:00.000Z",
            },
        ],
    },
    {
        user: {
            _id: "user_5",
            name: "Noah Mitchell",
            handle: "noahmitchell",
            avatar: "https://i.pravatar.cc/150?img=16",
        },
        stories: [
            {
                _id: "story_7",
                user: {
                    _id: "user_5",
                    name: "Noah Mitchell",
                    handle: "noahmitchell",
                    avatar: "https://i.pravatar.cc/150?img=16",
                },
                mediaUrl: "https://picsum.photos/id/1074/800/1200",
                mediaType: "image",
                createdAt: "2026-06-01T07:45:00.000Z",
            },
        ],
    },
    {
        user: {
            _id: "user_6",
            name: "Ava Collins",
            handle: "avacollins",
            avatar: "https://i.pravatar.cc/150?img=17",
        },
        stories: [
            {
                _id: "story_8",
                user: {
                    _id: "user_6",
                    name: "Ava Collins",
                    handle: "avacollins",
                    avatar: "https://i.pravatar.cc/150?img=17",
                },
                mediaUrl: "https://picsum.photos/id/1084/800/1200",
                mediaType: "image",
                createdAt: "2026-06-01T13:00:00.000Z",
            },
        ],
    },
];

export const dummyConversationData = [
    {
        _id: "conv_1",
        isGroup: false,
        participant: {
            _id: "user_1",
            name: "Ethan Parker",
            email: "ethan.parker@example.com",
            handle: "ethanparker",
            avatar: "https://i.pravatar.cc/150?img=12",
            isOnline: false,
            lastSeen: "2026-06-01T11:09:09.105Z",
        },
        lastMessage: {
            _id: "msg_1",
            sender: "current_user",
            receiver: "user_1",
            conversationId: "conv_1",
            text: "Hey Ethan, how's the project going?",
            read: false,
            createdAt: "2026-06-01T12:53:13.642Z",
            updatedAt: "2026-06-01T12:53:13.642Z",
        },
        updatedAt: "2026-06-01T12:53:13.701Z",
    },
    {
        _id: "6a1d7f7086157496e5ece8bf",
        isGroup: false,
        participant: {
            _id: "user_2",
            name: "Olivia Bennett",
            email: "olivia.bennett@example.com",
            handle: "oliviabennett",
            avatar: "https://i.pravatar.cc/150?img=13",
            isOnline: true,
            lastSeen: "2026-05-22T12:41:24.076Z",
        },
        lastMessage: {
            _id: "msg_2",
            sender: "user_2",
            receiver: "current_user",
            conversationId: "6a1d7f7086157496e5ece8bf",
            text: "Let's catch up tomorrow.",
            read: true,
            createdAt: "2026-06-01T12:52:51.077Z",
            updatedAt: "2026-06-01T12:52:51.077Z",
        },
        updatedAt: "2026-06-01T12:52:51.122Z",
    },
    {
        _id: "6a1d7f7086157496e5ece8c0",
        isGroup: false,
        participant: {
            _id: "user_3",
            name: "Liam Carter",
            email: "liam.carter@example.com",
            handle: "liamcarter",
            avatar: "https://i.pravatar.cc/150?img=14",
            isOnline: false,
            lastSeen: "2026-05-30T09:15:10.000Z",
        },
        lastMessage: {
            _id: "msg_3",
            sender: "current_user",
            receiver: "user_3",
            conversationId: "6a1d7f7086157496e5ece8c0",
            text: "Thanks for the update.",
            read: true,
            createdAt: "2026-06-01T10:12:20.000Z",
            updatedAt: "2026-06-01T10:12:20.000Z",
        },
        updatedAt: "2026-06-01T10:12:20.000Z",
    },
    {
        _id: "6a1d7f7086157496e5ece8c1",
        isGroup: false,
        participant: {
            _id: "user_4",
            name: "Sophia Reed",
            email: "sophia.reed@example.com",
            handle: "sophiareed",
            avatar: "https://i.pravatar.cc/150?img=15",
            isOnline: true,
            lastSeen: "2026-06-01T13:05:00.000Z",
        },
        lastMessage: {
            _id: "msg_4",
            sender: "user_4",
            receiver: "current_user",
            conversationId: "6a1d7f7086157496e5ece8c1",
            mediaUrl: "https://picsum.photos/400/300",
            mediaType: "image",
            read: false,
            createdAt: "2026-06-01T13:04:30.000Z",
            updatedAt: "2026-06-01T13:04:30.000Z",
        },
        updatedAt: "2026-06-01T13:04:30.000Z",
    },
    {
        _id: "6a1d7f7086157496e5ece8c2",
        isGroup: false,
        participant: {
            _id: "user_5",
            name: "Noah Mitchell",
            email: "noah.mitchell@example.com",
            handle: "noahmitchell",
            avatar: "https://i.pravatar.cc/150?img=16",
            isOnline: false,
            lastSeen: "2026-05-29T18:40:00.000Z",
        },
        lastMessage: {
            _id: "msg_5",
            sender: "user_5",
            receiver: "current_user",
            conversationId: "6a1d7f7086157496e5ece8c2",
            text: "Can you review my PR?",
            read: false,
            createdAt: "2026-06-01T08:45:00.000Z",
            updatedAt: "2026-06-01T08:45:00.000Z",
        },
        updatedAt: "2026-06-01T08:45:00.000Z",
    },
    {
        _id: "6a1d7f7086157496e5ece8c3",
        isGroup: false,
        participant: {
            _id: "user_6",
            name: "Ava Collins",
            email: "ava.collins@example.com",
            handle: "avacollins",
            avatar: "https://i.pravatar.cc/150?img=17",
            isOnline: true,
            lastSeen: "2026-06-01T13:10:00.000Z",
        },
        lastMessage: {
            _id: "msg_6",
            sender: "current_user",
            receiver: "user_6",
            conversationId: "6a1d7f7086157496e5ece8c3",
            text: "See you at the meeting.",
            read: true,
            createdAt: "2026-06-01T11:30:00.000Z",
            updatedAt: "2026-06-01T11:30:00.000Z",
        },
        updatedAt: "2026-06-01T11:30:00.000Z",
    },
];

export const dummyMessages = [
    {
        _id: "msg_1",
        sender: "user_1",
        receiver: "current_user",
        conversationId: "conv_1",
        text: "Hey Dev 👋",
        read: true,
        createdAt: "2026-06-01T09:00:00.000Z",
        updatedAt: "2026-06-01T09:00:00.000Z",
    },
    {
        _id: "msg_2",
        sender: "current_user",
        receiver: "user_1",
        conversationId: "conv_1",
        text: "Hey Ethan! What's up?",
        read: true,
        createdAt: "2026-06-01T09:01:15.000Z",
        updatedAt: "2026-06-01T09:01:15.000Z",
    },
    {
        _id: "msg_3",
        sender: "user_1",
        receiver: "current_user",
        conversationId: "conv_1",
        text: "Not much, just wrapping up some work. How's your AI thumbnail project going?",
        read: true,
        createdAt: "2026-06-01T09:02:40.000Z",
        updatedAt: "2026-06-01T09:02:40.000Z",
    },
    {
        _id: "msg_4",
        sender: "current_user",
        receiver: "user_1",
        conversationId: "conv_1",
        text: "Pretty good! Working on improving image quality and generation speed.",
        read: true,
        createdAt: "2026-06-01T09:04:05.000Z",
        updatedAt: "2026-06-01T09:04:05.000Z",
    },
    {
        _id: "msg_5",
        sender: "user_1",
        receiver: "current_user",
        conversationId: "conv_1",
        text: "Nice. Are you using Gemini or Flux models?",
        read: true,
        createdAt: "2026-06-01T09:05:30.000Z",
        updatedAt: "2026-06-01T09:05:30.000Z",
    },
    {
        _id: "msg_6",
        sender: "current_user",
        receiver: "user_1",
        conversationId: "conv_1",
        text: "Currently testing both. Flux gives great results, but Gemini is getting better.",
        read: true,
        createdAt: "2026-06-01T09:07:00.000Z",
        updatedAt: "2026-06-01T09:07:00.000Z",
    },
    {
        _id: "msg_7",
        sender: "user_1",
        receiver: "current_user",
        conversationId: "conv_1",
        text: "Makes sense. Have you launched it publicly yet?",
        read: true,
        createdAt: "2026-06-01T09:08:45.000Z",
        updatedAt: "2026-06-01T09:08:45.000Z",
    },
    {
        _id: "msg_8",
        sender: "current_user",
        receiver: "user_1",
        conversationId: "conv_1",
        text: "Not yet. Finishing payments and subscription management first.",
        read: true,
        createdAt: "2026-06-01T09:10:12.000Z",
        updatedAt: "2026-06-01T09:10:12.000Z",
    },
    {
        _id: "msg_9",
        sender: "user_1",
        receiver: "current_user",
        conversationId: "conv_1",
        text: "Good call. Better to get the business side right before scaling.",
        read: true,
        createdAt: "2026-06-01T09:11:48.000Z",
        updatedAt: "2026-06-01T09:11:48.000Z",
    },
    {
        _id: "msg_10",
        sender: "current_user",
        receiver: "user_1",
        conversationId: "conv_1",
        text: "Exactly. Also working on improving the thumbnail editor.",
        read: true,
        createdAt: "2026-06-01T09:13:00.000Z",
        updatedAt: "2026-06-01T09:13:00.000Z",
    },
    {
        _id: "msg_11",
        sender: "user_1",
        receiver: "current_user",
        conversationId: "conv_1",
        text: "Sounds exciting! Send me a screenshot when you're done.",
        read: true,
        createdAt: "2026-06-01T09:14:30.000Z",
        updatedAt: "2026-06-01T09:14:30.000Z",
    },
    {
        _id: "msg_12",
        sender: "current_user",
        receiver: "user_1",
        conversationId: "conv_1",
        mediaUrl: "https://picsum.photos/800/600",
        mediaType: "image",
        read: false,
        createdAt: "2026-06-01T09:15:50.000Z",
        updatedAt: "2026-06-01T09:15:50.000Z",
    },
    {
        _id: "msg_13",
        sender: "current_user",
        receiver: "user_1",
        conversationId: "conv_1",
        text: "Here's the latest design. Let me know what you think.",
        read: false,
        createdAt: "2026-06-01T09:16:05.000Z",
        updatedAt: "2026-06-01T09:16:05.000Z",
    },
];

export const dummyUsers = [
    {
        _id: "1",
        name: "Ethan Parker",
        handle: "ethanparker",
        email: "ethan@example.com",
        bio: "Hey there! I am using InstaChat.",
        isOnline: true,
        lastSeen: "2026-05-22T12:41:24.076Z",
        avatar: "https://i.pravatar.cc/150?img=12",
    },
    {
        _id: "2",
        name: "Olivia Bennett",
        handle: "oliviabennett",
        email: "olivia@example.com",
        bio: "Hey there! I am using InstaChat.",
        isOnline: true,
        lastSeen: "2026-05-22T12:41:24.076Z",
        avatar: "https://i.pravatar.cc/150?img=13",
    },
    {
        _id: "3",
        name: "Liam Carter",
        handle: "liamcarter",
        email: "liam@example.com",
        bio: "Hey there! I am using InstaChat.",
        isOnline: true,
        lastSeen: "2026-05-22T12:41:24.076Z",
        avatar: "https://i.pravatar.cc/150?img=14",
    },
    {
        _id: "4",
        name: "Sophia Reed",
        handle: "sophiareed",
        email: "sophia@example.com",
        bio: "Hey there! I am using InstaChat.",
        isOnline: true,
        lastSeen: "2026-05-22T12:41:24.076Z",
        avatar: "https://i.pravatar.cc/150?img=15",
    },
    {
        _id: "5",
        name: "Noah Mitchell",
        handle: "noahmitchell",
        email: "noah@example.com",
        bio: "Hey there! I am using InstaChat.",
        isOnline: true,
        lastSeen: "2026-05-22T12:41:24.076Z",
        avatar: "https://i.pravatar.cc/150?img=16",
    },
    {
        _id: "6",
        name: "Ava Collins",
        handle: "avacollins",
        email: "ava@example.com",
        bio: "Hey there! I am using InstaChat.",
        isOnline: true,
        lastSeen: "2026-05-22T12:41:24.076Z",
        avatar: "https://i.pravatar.cc/150?img=17",
    },
    {
        _id: "7",
        name: "Mason Brooks",
        handle: "masonbrooks",
        email: "mason@example.com",
        bio: "Hey there! I am using InstaChat.",
        isOnline: true,
        lastSeen: "2026-05-22T12:41:24.076Z",
        avatar: "https://i.pravatar.cc/150?img=18",
    },
    {
        _id: "8",
        name: "Isabella Hayes",
        handle: "isabellahayes",
        email: "isabella@example.com",
        bio: "Hey there! I am using InstaChat.",
        isOnline: true,
        lastSeen: "2026-05-22T12:41:24.076Z",
        avatar: "https://i.pravatar.cc/150?img=19",
    },
    {
        _id: "9",
        name: "Lucas Foster",
        handle: "lucasfoster",
        email: "lucas@example.com",
        bio: "Hey there! I am using InstaChat.",
        isOnline: true,
        lastSeen: "2026-05-22T12:41:24.076Z",
        avatar: "https://i.pravatar.cc/150?img=20",
    },
    {
        _id: "10",
        name: "Mia Turner",
        handle: "miaturner",
        email: "mia@example.com",
        bio: "Hey there! I am using InstaChat.",
        isOnline: true,
        lastSeen: "2026-05-22T12:41:24.076Z",
        avatar: "https://i.pravatar.cc/150?img=21",
    },
];

export const dummyUserProfile = {
    _id: "current_user",
    name: "GreatStack",
    email: "greatstack@example.com",
    handle: "greatstack",
    avatar: "https://yt3.ggpht.com/SxtxAT2eoNsERZyC-2Q9t3YhFC0IPhlaYOFA8rciY3BkhfoR9VPAx5n8A8L6QNG3vjFXSsB7rQ=s240-c-k-c0x00ffffff-no-rj",
    bio: "Hey there! I am using InstaChat.",
    isOnline: true,
    lastSeen: "2026-06-02T07:52:28.905Z",
};
